;;; darkman-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from darkman.el

(autoload 'darkman-current-mode "darkman" "\
Return the mode of the service.
When MESSAGE is non-nil, print the current mode to the echo area instead.

(fn &optional MESSAGE)" t)
(autoload 'darkman-toggle "darkman" "\
Toggle the mode of the service." t)
(autoload 'darkman-set-theme "darkman" "\
Set the theme to match that of the current mode." t)
(defvar darkman-mode nil "\
Non-nil if Darkman mode is enabled.
See the `darkman-mode' command
for a description of this minor mode.
Setting this variable directly does not take effect;
either customize it (see the info node `Easy Customization')
or call the function `darkman-mode'.")
(custom-autoload 'darkman-mode "darkman" nil)
(autoload 'darkman-mode "darkman" "\
Minor mode providing integration with Darkman.

This is a global minor mode.  If called interactively, toggle the
`Darkman mode' mode.  If the prefix argument is positive, enable the
mode, and if it is zero or negative, disable the mode.

If called from Lisp, toggle the mode if ARG is `toggle'.  Enable the
mode if ARG is nil, omitted, or is a positive number.  Disable the mode
if ARG is a negative number.

To check whether the minor mode is enabled in the current buffer,
evaluate `(default-value \\='darkman-mode)'.

The mode's hook is called both when the mode is enabled and when it is
disabled.

(fn &optional ARG)" t)
(register-definition-prefixes "darkman" '("darkman-"))

;;; End of scraped data

(provide 'darkman-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; darkman-autoloads.el ends here
