;;; koishi-theme-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from koishi-theme.el

(defcustom koishi-theme-background-mode 'dark "\
Koishi theme is a dark theme.
Set this variable to \\='light to use complementary color.
Its value will be synchronized to `frame-background-mode'." :set #'(lambda (var value) (set-default var value) (customize-set-variable 'frame-background-mode value)) :initialize #'custom-initialize-set :type '(choice (const dark) (const light)) :group 'koishi)
(custom-autoload 'koishi-theme-background-mode "koishi-theme" nil)
(defvar koishi-theme-afterglow-color nil "\
Experimental Feature: RGB Color of afterglow for all initial colors.")
(custom-autoload 'koishi-theme-afterglow-color "koishi-theme" t)
(defvar koishi-theme-afterglow-level 0 "\
Experimental Feature: Blend degree of afterglow for all initial colors.")
(custom-autoload 'koishi-theme-afterglow-level "koishi-theme" t)
(defvar koishi-theme-hsl-bias '(0 0 0) "\
Experimental Feature: HSL bias value for all initial colors.")
(custom-autoload 'koishi-theme-hsl-bias "koishi-theme" t)
(defvar koishi-theme-hsl-bias-random 0 "\
Experimental Feature: Random range of HSL bias for all initial colors.")
(custom-autoload 'koishi-theme-hsl-bias-random "koishi-theme" t)
(defvar koishi-theme-effects '(koishi-theme-effect--complement koishi-theme-effect--hsl-bias koishi-theme-effect--afterglow) "\
A list of effects to be applied to RGB color strings one by one.
Set this variable to nil if you think it slowed down your startup.")
(custom-autoload 'koishi-theme-effects "koishi-theme" t)
(autoload 'koishi-theme-reset-faces "koishi-theme" "\
A wrapper to reset koishi-theme after it is loaded.
This is achieved by calling `custom-set-faces'." t)
(when load-file-name (add-to-list 'custom-theme-load-path (file-name-as-directory (file-name-directory load-file-name))))
(register-definition-prefixes "koishi-theme" '("koishi"))

;;; End of scraped data

(provide 'koishi-theme-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; koishi-theme-autoloads.el ends here
