;;; play-crystal-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from play-crystal.el

(autoload 'play-crystal-insert "play-crystal" "\
Insert code identified by RUN-ID into the current buffer.

(fn RUN-ID)" t)
(autoload 'play-crystal-insert-another-buffer "play-crystal" "\
Insert code identified by RUN-ID into another buffer.

(fn RUN-ID)" t)
(autoload 'play-crystal-browse "play-crystal" "\
Show code identified by RUN-ID in a browser using 'browse-url'.

(fn RUN-ID)" t)
(autoload 'play-crystal-submit-region "play-crystal" "\
Create new run submitting code from the current region." t)
(autoload 'play-crystal-submit-buffer "play-crystal" "\
Create new run submitting code from the current buffer." t)
(register-definition-prefixes "play-crystal" '("play-crystal-"))

;;; End of scraped data

(provide 'play-crystal-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; play-crystal-autoloads.el ends here
