;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
	backward-kill-sexp
	c-electric-semi&comma
	wdired-exit
	))

(setq mc/cmds-to-run-once
      '(
	dired-do-compress-to
	dired-find-alternate-file
	dired-sort-toggle-or-edit
	dired-unmark-backward
	wdired--self-insert
	wdired-next-line
	wdired-previous-line
	xref-find-references
	))
